"use strict";

const {
  CHANNEL_SLOT_MANIFEST_VERSION,
  CHANNEL_SLOT_MANIFEST_SCHEMA_VERSION,
  CHANNEL_STATUS,
  DEFAULT_CHANNEL_SLOT_MANIFEST,
  createChannelSlotManifest,
} = require("../channels");

const {
  THIN_BLOCK_ROUTER_VERSION,
  CHANNEL_ID,
  ROUTE_STATUS,
  SUPPORTED_BLOCK_TYPE_SET,
  RESERVED_CHANNEL_SET,
  createThinBlockRouter,
} = require("./ThinBlockRouter");

module.exports = {
  CHANNEL_SLOT_MANIFEST_VERSION,
  CHANNEL_SLOT_MANIFEST_SCHEMA_VERSION,
  THIN_BLOCK_ROUTER_VERSION,
  CHANNEL_ID,
  CHANNEL_STATUS,
  DEFAULT_CHANNEL_SLOT_MANIFEST,
  createChannelSlotManifest,
  ROUTE_STATUS,
  SUPPORTED_BLOCK_TYPE_SET,
  RESERVED_CHANNEL_SET,
  createThinBlockRouter,
};
