"use strict";

const CSHARP_KEYWORDS = new Set([
  "abstract",
  "as",
  "base",
  "bool",
  "break",
  "byte",
  "case",
  "catch",
  "char",
  "checked",
  "class",
  "const",
  "continue",
  "decimal",
  "default",
  "delegate",
  "do",
  "double",
  "else",
  "enum",
  "event",
  "explicit",
  "extern",
  "false",
  "finally",
  "fixed",
  "float",
  "for",
  "foreach",
  "goto",
  "if",
  "implicit",
  "in",
  "int",
  "interface",
  "internal",
  "is",
  "lock",
  "long",
  "namespace",
  "new",
  "null",
  "object",
  "operator",
  "out",
  "override",
  "params",
  "private",
  "protected",
  "public",
  "readonly",
  "ref",
  "return",
  "sbyte",
  "sealed",
  "short",
  "sizeof",
  "stackalloc",
  "static",
  "string",
  "struct",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "uint",
  "ulong",
  "unchecked",
  "unsafe",
  "ushort",
  "using",
  "virtual",
  "void",
  "volatile",
  "while",
]);

function pascalCase(input) {
  const joined = String(input || "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
  if (!joined) {
    return "Unnamed";
  }
  if (/^\d/.test(joined)) {
    return `N${joined}`;
  }
  return joined;
}

function escapeCSharpString(input) {
  return String(input || "")
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"');
}

function sanitizeFieldName(input) {
  const raw = String(input || "field").replace(/[^a-zA-Z0-9_]/g, "_");
  const withPrefix = /^\d/.test(raw) ? `_${raw}` : raw;
  if (CSHARP_KEYWORDS.has(withPrefix)) {
    return `@${withPrefix}`;
  }
  return withPrefix;
}

function mapScalarType(typeName) {
  switch (typeName) {
    case "string":
      return "string";
    case "integer":
      return "int";
    case "number":
      return "double";
    case "boolean":
      return "bool";
    default:
      return "string";
  }
}

function mapSchemaTypeToCSharp(schemaNode) {
  const schema = schemaNode && typeof schemaNode === "object" ? schemaNode : {};
  if (schema.type === "array") {
    const itemType = mapScalarType(schema.items && schema.items.type);
    return `${itemType}[]`;
  }
  return mapScalarType(schema.type);
}

function emitRequiredArray(requiredFields) {
  const values = Array.isArray(requiredFields) ? requiredFields : [];
  if (values.length === 0) {
    return "new string[0]";
  }
  const encoded = values.map((field) => `"${escapeCSharpString(field)}"`).join(", ");
  return `new[] { ${encoded} }`;
}

function emitFieldLines(inputSchema) {
  const schema = inputSchema && typeof inputSchema === "object" ? inputSchema : {};
  const properties =
    schema.properties && typeof schema.properties === "object" ? schema.properties : {};
  const entries = Object.entries(properties);
  if (entries.length === 0) {
    return ["        // No explicit input properties are declared for this tool."];
  }
  return entries.map(([propertyName, propertySchema]) => {
    const fieldName = sanitizeFieldName(propertyName);
    const fieldType = mapSchemaTypeToCSharp(propertySchema);
    return `        public ${fieldType} ${fieldName};`;
  });
}

function emitToolDto(tool) {
  const className = `${pascalCase(tool.name)}RequestDto`;
  const inputSchema = tool && tool.input && typeof tool.input === "object" ? tool.input : {};
  const requiredFields = Array.isArray(inputSchema.required) ? inputSchema.required : [];
  const fieldLines = emitFieldLines(inputSchema).join("\n");
  return `    [Serializable]
    public sealed class ${className}
    {
        public const string ToolName = "${escapeCSharpString(tool.name)}";
        public static readonly string[] RequiredFields = ${emitRequiredArray(requiredFields)};

${fieldLines}
    }`;
}

function emitDtosCs(dictionary) {
  const tools = Array.isArray(dictionary.tools) ? dictionary.tools : [];
  const blocks = tools.map(emitToolDto).join("\n\n");
  return `// <auto-generated />
using System;

namespace UnityAI.Editor.Codex.Generated.Ssot
{
${blocks}
}
`;
}

module.exports = {
  emitDtosCs,
};
