"use strict";

const { LOCAL_STATIC_TOOL_NAMES } = require("../../shared/localStaticToolNames");

const UNSUPPORTED_TOOL_NAMES = new Set([
  "instantiate_prefab",
  "get_unity_task_status",
  "cancel_unity_task",
  "submit_unity_task",
  "apply_script_actions",
]);

const DEPRECATED_TOOL_CONFIG = {
  apply_visual_actions:
    "apply_visual_actions is deprecated in SSOT-only mode. Use fine-grained SSOT write tools or execute_unity_transaction.",
  set_ui_properties:
    "set_ui_properties is deprecated in SSOT-only mode. Use fine-grained SSOT UI tools.",
};

function pascalCase(input) {
  const joined = String(input || "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
  if (!joined) {
    return "Unnamed";
  }
  if (/^\d/.test(joined)) {
    return `N${joined}`;
  }
  return joined;
}

function requestDtoClassName(toolName) {
  return `${pascalCase(toolName)}RequestDto`;
}

function executorClassName(toolName) {
  return `${pascalCase(toolName)}SsotExecutor`;
}

function emitExecutorBinding(toolName) {
  const requestClass = requestDtoClassName(toolName);
  const executorClass = executorClassName(toolName);
  const creator =
    toolName === "execute_unity_transaction"
      ? `() => new ${executorClass}(nestedToolDispatcher)`
      : `() => new ${executorClass}()`;

  return `            bindings[${requestClass}.ToolName] =
                SsotDispatchBindingFactory.CreateExecutorBinding<${requestClass}, ${executorClass}>(
                    ${requestClass}.ToolName,
                    executorFactory,
                    ${creator},
                    (executor, request) => executor.Execute(request),
                    "SSOT request type mismatch for ${toolName}.");`;
}

function emitDeprecatedBinding(toolName, deprecatedMessage) {
  const requestClass = requestDtoClassName(toolName);
  return `            bindings[${requestClass}.ToolName] =
                SsotDispatchBindingFactory.CreateDeprecatedBinding<${requestClass}>(
                    ${requestClass}.ToolName,
                    "SSOT request type mismatch for ${toolName}.",
                    "${deprecatedMessage.replace(/\\/g, "\\\\").replace(/\"/g, "\\\"")}");`;
}

function emitUnsupportedBinding(toolName) {
  const requestClass = requestDtoClassName(toolName);
  return `            bindings[${requestClass}.ToolName] =
                SsotDispatchBindingFactory.CreateUnsupportedBinding(${requestClass}.ToolName);`;
}

function emitToolBinding(toolName) {
  if (Object.prototype.hasOwnProperty.call(DEPRECATED_TOOL_CONFIG, toolName)) {
    return emitDeprecatedBinding(toolName, DEPRECATED_TOOL_CONFIG[toolName]);
  }

  if (UNSUPPORTED_TOOL_NAMES.has(toolName) || LOCAL_STATIC_TOOL_NAMES.has(toolName)) {
    return emitUnsupportedBinding(toolName);
  }

  return emitExecutorBinding(toolName);
}

function emitDispatcherBindingsCs(dictionary) {
  const tools = Array.isArray(dictionary && dictionary.tools)
    ? dictionary.tools
    : [];
  const toolNames = tools
    .map((tool) =>
      tool && typeof tool === "object" ? String(tool.name || "").trim() : ""
    )
    .filter((name) => !!name);
  const bindingLines = toolNames.map((toolName) => emitToolBinding(toolName)).join("\n\n");

  return `// <auto-generated />
using System;
using System.Collections.Generic;
using UnityAI.Editor.Codex.Infrastructure.Ssot;
using UnityAI.Editor.Codex.Infrastructure.Ssot.Executors;

namespace UnityAI.Editor.Codex.Generated.Ssot
{
    public static class SsotDispatchBindings
    {
        public static IReadOnlyDictionary<string, ISsotDispatchBinding> CreateBindingMap(
            ISsotExecutorFactory executorFactory,
            Func<string, string, SsotDispatchResponse> nestedToolDispatcher)
        {
            if (executorFactory == null)
            {
                throw new ArgumentNullException("executorFactory");
            }

            if (nestedToolDispatcher == null)
            {
                throw new ArgumentNullException("nestedToolDispatcher");
            }

            var bindings = new Dictionary<string, ISsotDispatchBinding>(StringComparer.Ordinal);
${bindingLines}

            return bindings;
        }
    }
}
`;
}

module.exports = {
  emitDispatcherBindingsCs,
};
