"use strict";

function pascalCase(input) {
  const joined = String(input || "")
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1).toLowerCase())
    .join("");
  if (!joined) {
    return "Unnamed";
  }
  if (/^\d/.test(joined)) {
    return `N${joined}`;
  }
  return joined;
}

function emitRouteCase(tool) {
  const className = `${pascalCase(tool.name)}RequestDto`;
  return `                case ${className}.ToolName:
                    return TryDeserialize<${className}>(payloadJson, out requestDto, out errorMessage);`;
}

function emitTypedMethod(tool) {
  const className = `${pascalCase(tool.name)}RequestDto`;
  const methodName = `TryDeserialize${pascalCase(tool.name)}`;
  return `        public static bool ${methodName}(string payloadJson, out ${className} requestDto, out string errorMessage)
        {
            requestDto = null;
            errorMessage = null;
            if (!TryDeserialize<${className}>(payloadJson, out var boxedRequest, out errorMessage))
            {
                return false;
            }

            requestDto = (${className})boxedRequest;
            return true;
        }`;
}

function emitBindingsCs(dictionary) {
  const tools = Array.isArray(dictionary.tools) ? dictionary.tools : [];
  const cases = tools.map((tool) => emitRouteCase(tool)).join("\n");
  const typedMethods = tools.map((tool) => emitTypedMethod(tool)).join("\n\n");
  return `// <auto-generated />
using System;
using UnityEngine;

namespace UnityAI.Editor.Codex.Generated.Ssot
{
    [Serializable]
    public sealed class SsotToolEnvelopeDto
    {
        public string tool_name;
        public string payload_json;
    }

    public static class SsotRequestRouter
    {
        public static bool TryDeserializeEnvelope(string envelopeJson, out object requestDto, out string errorMessage)
        {
            requestDto = null;
            errorMessage = null;

            if (string.IsNullOrWhiteSpace(envelopeJson))
            {
                errorMessage = "SSOT envelope JSON is empty.";
                return false;
            }

            SsotToolEnvelopeDto envelope;
            try
            {
                envelope = JsonUtility.FromJson<SsotToolEnvelopeDto>(envelopeJson);
            }
            catch (Exception ex)
            {
                errorMessage = "SSOT envelope deserialization failed: " + ex.Message;
                return false;
            }

            if (envelope == null)
            {
                errorMessage = "SSOT envelope deserialization returned null.";
                return false;
            }

            return TryDeserializeByToolName(envelope.tool_name, envelope.payload_json, out requestDto, out errorMessage);
        }

        public static bool TryDeserializeByToolName(string toolName, string payloadJson, out object requestDto, out string errorMessage)
        {
            requestDto = null;
            errorMessage = null;
            switch ((toolName ?? string.Empty).Trim())
            {
${cases}
                default:
                    errorMessage = "Unsupported SSOT tool: " + toolName;
                    return false;
            }
        }

${typedMethods}

        private static bool TryDeserialize<T>(string payloadJson, out object requestDto, out string errorMessage)
            where T : class
        {
            requestDto = null;
            errorMessage = null;

            if (string.IsNullOrWhiteSpace(payloadJson))
            {
                errorMessage = "SSOT payload JSON is empty.";
                return false;
            }

            if (string.Equals(typeof(T).Name, "ExecuteUnityTransactionRequestDto", StringComparison.Ordinal))
            {
                if (!UnityAI.Editor.Codex.Infrastructure.Ssot.Transaction.ExecuteUnityTransactionPayloadParser.TryDeserialize(
                        payloadJson,
                        out UnityAI.Editor.Codex.Generated.Ssot.ExecuteUnityTransactionRequestDto executeUnityTransactionRequest,
                        out errorMessage))
                {
                    return false;
                }

                requestDto = executeUnityTransactionRequest;
                return true;
            }

            try
            {
                var parsed = JsonUtility.FromJson<T>(payloadJson);
                if (parsed == null)
                {
                    errorMessage = "SSOT payload deserialization returned null for type " + typeof(T).Name + ".";
                    return false;
                }

                requestDto = parsed;
                return true;
            }
            catch (Exception ex)
            {
                errorMessage = "SSOT payload deserialization failed for type " + typeof(T).Name + ": " + ex.Message;
                return false;
            }
        }
    }
}
`;
}

module.exports = {
  emitBindingsCs,
};
