"use strict";

module.exports = [
  require("./submit_unity_task"),
  require("./get_unity_task_status"),
  require("./cancel_unity_task"),
  require("./get_current_selection"),
  require("./get_gameobject_components"),
  require("./get_hierarchy_subtree"),
  require("./apply_script_actions"),
  require("./apply_visual_actions"),
  require("./set_ui_properties"),
  require("./set_serialized_property"),
  require("./get_action_catalog"),
  require("./get_action_schema"),
  require("./get_tool_schema"),
  require("./get_write_contract_bundle"),
  require("./preflight_validate_write_payload"),
  require("./setup_cursor_mcp"),
  require("./verify_mcp_setup"),
  require("./capture_scene_screenshot"),
  require("./get_ui_tree"),
  require("./get_ui_overlay_report"),
  require("./get_serialized_property_tree"),
  require("./hit_test_ui_at_viewport_point"),
  require("./validate_ui_layout"),
  require("./hit_test_ui_at_screen_point"),
  require("./list_assets_in_folder"),
  require("./get_scene_roots"),
  require("./find_objects_by_component"),
  require("./query_prefab_info"),
];
