"use strict";

const SSOT_TOKEN_PREFIX = "ssot_rt_";
const SSOT_TOKEN_MIN_LENGTH = 24;
const SSOT_TOKEN_HARD_MAX_AGE_MS = 3 * 60 * 1000;
const SSOT_TOKEN_CACHE_LIMIT = 1024;
const SSOT_UNKNOWN_SCENE_REVISION = "scene_rev_unknown";

const SSOT_TOKEN_ERROR_CODES = Object.freeze({
  TOKEN_UNKNOWN: "E_TOKEN_UNKNOWN",
  TOKEN_EXPIRED: "E_TOKEN_EXPIRED",
  SCENE_REVISION_DRIFT: "E_SCENE_REVISION_DRIFT",
});

module.exports = {
  SSOT_TOKEN_PREFIX,
  SSOT_TOKEN_MIN_LENGTH,
  SSOT_TOKEN_HARD_MAX_AGE_MS,
  SSOT_TOKEN_CACHE_LIMIT,
  SSOT_UNKNOWN_SCENE_REVISION,
  SSOT_TOKEN_ERROR_CODES,
};
