"use strict";

const BLOCK_ERROR_ALIAS_TO_CANONICAL = Object.freeze({
  E_BLOCK_NOT_IMPLEMENTED: "E_PRECONDITION_FAILED",
  E_BLOCK_INTENT_KEY_UNSUPPORTED: "E_SCHEMA_INVALID",
  E_BLOCK_PIPELINE_DISABLED: "E_PRECONDITION_FAILED",
  E_BLOCK_SCHEMA_INVALID: "E_SCHEMA_INVALID",
  E_BLOCK_TYPE_UNSUPPORTED: "E_PRECONDITION_FAILED",
  E_BLOCK_CHANNEL_RESERVED: "E_PRECONDITION_FAILED",
  E_BLOCK_CHANNEL_UNSUPPORTED: "E_PRECONDITION_FAILED",
  E_BLOCK_VERIFY_FAILED: "E_PRECONDITION_FAILED",
  E_BLOCK_FALLBACK_NOT_ALLOWED: "E_PRECONDITION_FAILED",
});

module.exports = {
  BLOCK_ERROR_ALIAS_TO_CANONICAL,
};
