using System;
using System.Linq;
using System.Reflection;
using NUnit.Framework;
using UnityAI.Editor.Codex.Domain;

namespace UnityAI.Editor.Codex.Tests.EditMode
{
    public sealed class SidecarContractsSnapshotTests
    {
        [Test]
        public void ErrorResponse_FieldSnapshot_RemainsStable()
        {
            AssertFieldSnapshot(
                typeof(ErrorResponse),
                "status",
                "error_code",
                "message",
                "error_message",
                "suggestion",
                "recoverable");
        }

        [Test]
        public void UnityCapabilitiesContracts_FieldSnapshot_RemainsStable()
        {
            AssertFieldSnapshot(
                typeof(UnityCapabilitiesReportPayload),
                "capability_version",
                "actions");
            AssertFieldSnapshot(
                typeof(UnityCapabilityActionItem),
                "type",
                "anchor_policy",
                "description",
                "domain",
                "tier",
                "lifecycle",
                "undo_safety",
                "replacement_action_type",
                "action_data_schema");
            AssertFieldSnapshot(
                typeof(UnityActionDataSchema),
                "type",
                "required",
                "properties");
            AssertFieldSnapshot(
                typeof(UnityActionDataSchemaProperty),
                "name",
                "type",
                "description");
        }

        [Test]
        public void UnityActionResultPayload_FieldSnapshot_RemainsStable()
        {
            AssertFieldSnapshot(
                typeof(UnityActionResultPayload),
                "action_type",
                "target",
                "target_object_path",
                "target_object_id",
                "object_id",
                "component_assembly_qualified_name",
                "source_component_assembly_qualified_name",
                "created_object_path",
                "created_object_id",
                "name",
                "parent_object_path",
                "parent_object_id",
                "primitive_type",
                "ui_type",
                "success",
                "error_code",
                "error_message",
                "duration_ms");
        }

        [Test]
        public void UnityCaptureSceneScreenshotContracts_FieldSnapshot_RemainsStable()
        {
            AssertFieldSnapshot(
                typeof(UnityCaptureSceneScreenshotPayload),
                "view_mode",
                "capture_mode",
                "output_mode",
                "image_format",
                "width",
                "height",
                "jpeg_quality",
                "timeout_ms",
                "include_ui");
            AssertFieldSnapshot(
                typeof(UnityCaptureSceneScreenshotData),
                "requested_mode",
                "view_mode",
                "effective_mode",
                "capture_mode_effective",
                "fallback_reason",
                "diagnosis_tags",
                "output_mode",
                "image_format",
                "mime_type",
                "width",
                "height",
                "byte_size",
                "artifact_uri",
                "image_base64",
                "unity_state",
                "pixel_sanity",
                "camera_used",
                "game_view_rect_screen_px",
                "read_rect_screen_px",
                "pixels_per_point",
                "display_index",
                "read_timing",
                "editor_window_rect_screen_px",
                "include_gizmos_effective");
            AssertFieldSnapshot(
                typeof(UnityScreenshotRect),
                "x",
                "y",
                "width",
                "height");
            AssertFieldSnapshot(
                typeof(UnityScreenshotUnityState),
                "is_playing",
                "is_paused",
                "focused_view");
            AssertFieldSnapshot(
                typeof(UnityScreenshotPixelSanity),
                "is_all_black",
                "avg_luma",
                "std_luma",
                "unique_color_estimate");
            AssertFieldSnapshot(
                typeof(UnityScreenshotCameraUsed),
                "path",
                "instance_id",
                "target_display",
                "culling_mask",
                "clear_flags",
                "background_color");
            AssertFieldSnapshot(
                typeof(UnityHitTestUiAtScreenPointPayload),
                "view_mode",
                "x",
                "y",
                "reference_width",
                "reference_height",
                "max_results",
                "timeout_ms");
            AssertFieldSnapshot(
                typeof(UnityHitTestUiAtScreenPointData),
                "view_mode",
                "requested_x",
                "requested_y",
                "mapped_screen_x",
                "mapped_screen_y",
                "reference_width",
                "reference_height",
                "game_view_rect_screen_px",
                "read_rect_screen_px",
                "hit_found",
                "hit_count",
                "hits");
            AssertFieldSnapshot(
                typeof(UnityUiHitTestItem),
                "object_id",
                "path",
                "name",
                "rect_screen_px",
                "z_order_hint");
            AssertFieldSnapshot(
                typeof(UnityHitTestUiAtViewportPointPayload),
                "view",
                "coord_space",
                "coord_origin",
                "x",
                "y",
                "resolution",
                "scope",
                "max_results",
                "include_non_interactable",
                "timeout_ms");
            AssertFieldSnapshot(
                typeof(UnityHitTestUiAtViewportPointData),
                "view",
                "coord_space",
                "coord_origin",
                "requested_point",
                "mapped_point",
                "resolution",
                "runtime_resolution",
                "runtime_source",
                "approximate",
                "approx_reason",
                "confidence",
                "hit_count",
                "hits");
            AssertFieldSnapshot(
                typeof(UnityViewportPoint),
                "x",
                "y");
            AssertFieldSnapshot(
                typeof(UnityUiHitTestStackItem),
                "rank",
                "anchor",
                "object_id",
                "path",
                "name",
                "component",
                "interactable",
                "raycast_target",
                "rect_screen_px",
                "z_order_hint");
            AssertFieldSnapshot(
                typeof(UnityValidateUiLayoutPayload),
                "scope",
                "resolutions",
                "checks",
                "max_issues",
                "time_budget_ms",
                "layout_refresh_mode",
                "timeout_ms");
            AssertFieldSnapshot(
                typeof(UnityValidateUiLayoutData),
                "scope",
                "resolutions",
                "time_budget_ms",
                "runtime_resolution",
                "runtime_source",
                "partial",
                "truncated_reason",
                "issue_count",
                "runtime_resolution_name",
                "issues");
            AssertFieldSnapshot(
                typeof(UnityUiLayoutIssue),
                "anchor",
                "issue_type",
                "severity",
                "resolution",
                "details",
                "suggestion",
                "mode",
                "confidence",
                "approximate",
                "approx_reason");
        }

        [Test]
        public void UnityGetUiTreeContracts_FieldSnapshot_RemainsStable()
        {
            AssertFieldSnapshot(
                typeof(UnityGetUiTreePayload),
                "ui_system",
                "root_path",
                "include_inactive",
                "include_components",
                "include_layout",
                "include_interaction",
                "include_text_metrics",
                "max_depth",
                "node_budget",
                "char_budget",
                "resolution",
                "timeout_ms");
            AssertFieldSnapshot(
                typeof(UnityGetUiTreeData),
                "ui_system",
                "root_path",
                "include_inactive",
                "include_components",
                "include_layout",
                "include_interaction",
                "include_text_metrics",
                "max_depth",
                "node_budget",
                "char_budget",
                "returned_node_count",
                "truncated",
                "truncated_reason",
                "runtime_resolution",
                "runtime_source",
                "canvases",
                "roots");
            AssertFieldSnapshot(
                typeof(UnityUiCanvasInfo),
                "object_id",
                "path",
                "name",
                "active",
                "render_mode",
                "sorting_layer_id",
                "sorting_order",
                "is_root_canvas",
                "reference_resolution");
            AssertFieldSnapshot(
                typeof(UnityUiTreeNode),
                "anchor",
                "object_id",
                "path",
                "name",
                "depth",
                "active_self",
                "active_in_hierarchy",
                "sibling_index",
                "rect_transform",
                "rect_screen_px",
                "interaction",
                "text_metrics",
                "components",
                "components_summary",
                "children",
                "children_truncated_count");
            AssertFieldSnapshot(
                typeof(UnityUiRectTransformInfo),
                "anchor_min_x",
                "anchor_min_y",
                "anchor_max_x",
                "anchor_max_y",
                "pivot_x",
                "pivot_y",
                "anchored_position_x",
                "anchored_position_y",
                "size_delta_x",
                "size_delta_y",
                "offset_min_x",
                "offset_min_y",
                "offset_max_x",
                "offset_max_y");
            AssertFieldSnapshot(
                typeof(UnityUiComponentSummary),
                "type",
                "assembly_qualified_name",
                "enabled");
            AssertFieldSnapshot(
                typeof(UnityUiInteractionSummary),
                "raycast_target",
                "interactable",
                "blocks_raycast",
                "has_graphic_raycaster");
            AssertFieldSnapshot(
                typeof(UnityUiTextMetrics),
                "overflowing",
                "preferred_width",
                "preferred_height");
        }

        [Test]
        public void UnityPulledQueryContracts_FieldSnapshot_RemainsStable()
        {
            AssertFieldSnapshot(
                typeof(UnityPulledQuery),
                "query_id",
                "query_type",
                "query_contract_version",
                "request_id",
                "thread_id",
                "turn_id",
                "timeout_ms",
                "created_at",
                "pull_count",
                "query_payload_json",
                "payload");
        }

        private static void AssertFieldSnapshot(Type target, params string[] expectedFields)
        {
            Assert.NotNull(target);
            var actual = target
                .GetFields(BindingFlags.Public | BindingFlags.Instance)
                .Select((field) => field.Name)
                .ToArray();
            CollectionAssert.AreEquivalent(expectedFields, actual);
        }
    }
}
