// <auto-generated />
using System;

namespace UnityAI.Editor.Codex.Generated.Ssot
{
    [Serializable]
    public sealed class ModifyUiLayoutRequestDto
    {
        public const string ToolName = "modify_ui_layout";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "anchored_x", "anchored_y", "width", "height" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double anchored_x;
        public double anchored_y;
        public double width;
        public double height;
    }

    [Serializable]
    public sealed class SetComponentPropertiesRequestDto
    {
        public const string ToolName = "set_component_properties";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "component_type", "property_path", "value_kind" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string component_type;
        public string property_path;
        public string value_kind;
        public string value_string;
        public double value_number;
        public bool value_boolean;
    }

    [Serializable]
    public sealed class AddComponentRequestDto
    {
        public const string ToolName = "add_component";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "component_type" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string component_type;
    }

    [Serializable]
    public sealed class RemoveComponentRequestDto
    {
        public const string ToolName = "remove_component";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "component_type" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string component_type;
    }

    [Serializable]
    public sealed class ReplaceComponentRequestDto
    {
        public const string ToolName = "replace_component";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "source_component_type", "new_component_type" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string source_component_type;
        public string new_component_type;
    }

    [Serializable]
    public sealed class CreateObjectRequestDto
    {
        public const string ToolName = "create_object";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "parent_object_id", "parent_path", "new_object_name", "object_kind", "set_active" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string parent_object_id;
        public string parent_path;
        public string new_object_name;
        public string object_kind;
        public bool set_active;
    }

    [Serializable]
    public sealed class InstantiatePrefabRequestDto
    {
        public const string ToolName = "instantiate_prefab";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "parent_object_id", "parent_path", "prefab_asset_path" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string parent_object_id;
        public string parent_path;
        public string prefab_asset_path;
        public string instance_name;
        public bool world_position_stays;
    }

    [Serializable]
    public sealed class DeleteObjectRequestDto
    {
        public const string ToolName = "delete_object";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
    }

    [Serializable]
    public sealed class RenameObjectRequestDto
    {
        public const string ToolName = "rename_object";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "new_name" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string new_name;
    }

    [Serializable]
    public sealed class SetActiveRequestDto
    {
        public const string ToolName = "set_active";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "active" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public bool active;
    }

    [Serializable]
    public sealed class SetParentRequestDto
    {
        public const string ToolName = "set_parent";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "parent_object_id", "parent_path" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string parent_object_id;
        public string parent_path;
    }

    [Serializable]
    public sealed class SetSiblingIndexRequestDto
    {
        public const string ToolName = "set_sibling_index";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "sibling_index" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public int sibling_index;
    }

    [Serializable]
    public sealed class SetLocalPositionRequestDto
    {
        public const string ToolName = "set_local_position";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y", "z" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
        public double z;
    }

    [Serializable]
    public sealed class SetLocalRotationRequestDto
    {
        public const string ToolName = "set_local_rotation";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y", "z" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
        public double z;
    }

    [Serializable]
    public sealed class SetLocalScaleRequestDto
    {
        public const string ToolName = "set_local_scale";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y", "z" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
        public double z;
    }

    [Serializable]
    public sealed class SetWorldPositionRequestDto
    {
        public const string ToolName = "set_world_position";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y", "z" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
        public double z;
    }

    [Serializable]
    public sealed class SetWorldRotationRequestDto
    {
        public const string ToolName = "set_world_rotation";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y", "z" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
        public double z;
    }

    [Serializable]
    public sealed class ResetTransformRequestDto
    {
        public const string ToolName = "reset_transform";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
    }

    [Serializable]
    public sealed class SetRectAnchoredPositionRequestDto
    {
        public const string ToolName = "set_rect_anchored_position";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
    }

    [Serializable]
    public sealed class SetRectSizeDeltaRequestDto
    {
        public const string ToolName = "set_rect_size_delta";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
    }

    [Serializable]
    public sealed class SetRectPivotRequestDto
    {
        public const string ToolName = "set_rect_pivot";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "x", "y" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double x;
        public double y;
    }

    [Serializable]
    public sealed class SetRectAnchorsRequestDto
    {
        public const string ToolName = "set_rect_anchors";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "min_x", "min_y", "max_x", "max_y" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double min_x;
        public double min_y;
        public double max_x;
        public double max_y;
    }

    [Serializable]
    public sealed class SetCanvasGroupAlphaRequestDto
    {
        public const string ToolName = "set_canvas_group_alpha";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "alpha" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double alpha;
    }

    [Serializable]
    public sealed class SetLayoutElementRequestDto
    {
        public const string ToolName = "set_layout_element";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "min_width", "min_height", "preferred_width", "preferred_height", "flexible_width", "flexible_height", "ignore_layout" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double min_width;
        public double min_height;
        public double preferred_width;
        public double preferred_height;
        public double flexible_width;
        public double flexible_height;
        public bool ignore_layout;
    }

    [Serializable]
    public sealed class SetUiImageColorRequestDto
    {
        public const string ToolName = "set_ui_image_color";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "r", "g", "b", "a" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double r;
        public double g;
        public double b;
        public double a;
    }

    [Serializable]
    public sealed class SetUiImageRaycastTargetRequestDto
    {
        public const string ToolName = "set_ui_image_raycast_target";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "raycast_target" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public bool raycast_target;
    }

    [Serializable]
    public sealed class SetUiTextContentRequestDto
    {
        public const string ToolName = "set_ui_text_content";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "text" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string text;
    }

    [Serializable]
    public sealed class SetUiTextColorRequestDto
    {
        public const string ToolName = "set_ui_text_color";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "r", "g", "b", "a" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double r;
        public double g;
        public double b;
        public double a;
    }

    [Serializable]
    public sealed class SetUiTextFontSizeRequestDto
    {
        public const string ToolName = "set_ui_text_font_size";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "font_size" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public double font_size;
    }

    [Serializable]
    public sealed class ExecuteUnityTransactionRequestDto
    {
        public const string ToolName = "execute_unity_transaction";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "transaction_id", "steps_json" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string transaction_id;
        public string steps_json;
    }

    [Serializable]
    public sealed class DuplicateObjectRequestDto
    {
        public const string ToolName = "duplicate_object";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string duplicate_name;
    }

    [Serializable]
    public sealed class GetSceneSnapshotForWriteRequestDto
    {
        public const string ToolName = "get_scene_snapshot_for_write";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string scope_path;
    }

    [Serializable]
    public sealed class GetCurrentSelectionRequestDto
    {
        public const string ToolName = "get_current_selection";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
    }

    [Serializable]
    public sealed class GetGameobjectComponentsRequestDto
    {
        public const string ToolName = "get_gameobject_components";
        public static readonly string[] RequiredFields = new[] { "target_object_id", "target_path" };

        public string thread_id;
        public string target_object_id;
        public string target_path;
    }

    [Serializable]
    public sealed class GetHierarchySubtreeRequestDto
    {
        public const string ToolName = "get_hierarchy_subtree";
        public static readonly string[] RequiredFields = new[] { "target_object_id", "target_path" };

        public string thread_id;
        public string target_object_id;
        public string target_path;
        public int depth;
        public int node_budget;
        public int char_budget;
    }

    [Serializable]
    public sealed class GetSceneRootsRequestDto
    {
        public const string ToolName = "get_scene_roots";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string scene_path;
        public bool include_inactive;
    }

    [Serializable]
    public sealed class ListAssetsInFolderRequestDto
    {
        public const string ToolName = "list_assets_in_folder";
        public static readonly string[] RequiredFields = new[] { "folder_path" };

        public string thread_id;
        public string folder_path;
        public bool recursive;
        public bool include_meta;
        public int limit;
    }

    [Serializable]
    public sealed class FindObjectsByComponentRequestDto
    {
        public const string ToolName = "find_objects_by_component";
        public static readonly string[] RequiredFields = new[] { "component_query" };

        public string thread_id;
        public string component_query;
        public string scene_path;
        public string under_path;
        public bool include_inactive;
        public int limit;
    }

    [Serializable]
    public sealed class QueryPrefabInfoRequestDto
    {
        public const string ToolName = "query_prefab_info";
        public static readonly string[] RequiredFields = new[] { "prefab_path", "max_depth" };

        public string thread_id;
        public string prefab_path;
        public int max_depth;
        public int node_budget;
        public int char_budget;
        public bool include_components;
        public bool include_missing_scripts;
    }

    [Serializable]
    public sealed class GetUiTreeRequestDto
    {
        public const string ToolName = "get_ui_tree";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string ui_system;
        public string root_path;
        public string scope;
        public bool include_inactive;
        public bool include_components;
        public bool include_layout;
        public bool include_interaction;
        public bool include_text_metrics;
        public int max_depth;
        public int node_budget;
        public int char_budget;
        public string resolution;
        public int timeout_ms;
    }

    [Serializable]
    public sealed class GetUiOverlayReportRequestDto
    {
        public const string ToolName = "get_ui_overlay_report";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string root_path;
        public string scope;
        public bool include_inactive;
        public bool include_children_summary;
        public int max_nodes;
        public int max_children_per_canvas;
        public int timeout_ms;
    }

    [Serializable]
    public sealed class HitTestUiAtViewportPointRequestDto
    {
        public const string ToolName = "hit_test_ui_at_viewport_point";
        public static readonly string[] RequiredFields = new[] { "x", "y" };

        public string thread_id;
        public string view;
        public string coord_space;
        public string coord_origin;
        public double x;
        public double y;
        public int resolution_width;
        public int resolution_height;
        public string scope_root_path;
        public int max_results;
        public bool include_non_interactable;
        public int timeout_ms;
    }

    [Serializable]
    public sealed class ValidateUiLayoutRequestDto
    {
        public const string ToolName = "validate_ui_layout";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string scope_root_path;
        public string resolution_name;
        public int resolution_width;
        public int resolution_height;
        public string checks_csv;
        public int max_issues;
        public int time_budget_ms;
        public string layout_refresh_mode;
        public bool include_repair_plan;
        public int max_repair_suggestions;
        public string repair_style;
        public int timeout_ms;
    }

    [Serializable]
    public sealed class GetSerializedPropertyTreeRequestDto
    {
        public const string ToolName = "get_serialized_property_tree";
        public static readonly string[] RequiredFields = new[] { "target_object_id", "target_path", "component_assembly_qualified_name" };

        public string thread_id;
        public string target_object_id;
        public string target_path;
        public string component_assembly_qualified_name;
        public int component_index;
        public string root_property_path;
        public int depth;
        public string after_property_path;
        public int page_size;
        public int node_budget;
        public int char_budget;
        public bool include_value_summary;
        public bool include_non_visible;
        public int timeout_ms;
    }

    [Serializable]
    public sealed class CaptureSceneScreenshotRequestDto
    {
        public const string ToolName = "capture_scene_screenshot";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string view_mode;
        public string capture_mode;
        public string output_mode;
        public string image_format;
        public int width;
        public int height;
        public int jpeg_quality;
        public int max_base64_bytes;
        public int timeout_ms;
        public bool include_ui;
    }

    [Serializable]
    public sealed class GetActionCatalogRequestDto
    {
        public const string ToolName = "get_action_catalog";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string domain;
        public string tier;
        public string lifecycle;
        public int cursor;
        public int limit;
        public string catalog_version;
        public string if_none_match;
    }

    [Serializable]
    public sealed class GetActionSchemaRequestDto
    {
        public const string ToolName = "get_action_schema";
        public static readonly string[] RequiredFields = new[] { "action_type" };

        public string thread_id;
        public string action_type;
        public string catalog_version;
        public string if_none_match;
    }

    [Serializable]
    public sealed class GetToolSchemaRequestDto
    {
        public const string ToolName = "get_tool_schema";
        public static readonly string[] RequiredFields = new[] { "tool_name" };

        public string thread_id;
        public string tool_name;
    }

    [Serializable]
    public sealed class GetWriteContractBundleRequestDto
    {
        public const string ToolName = "get_write_contract_bundle";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string tool_name;
        public string action_type;
        public string catalog_version;
        public int budget_chars;
        public bool include_error_fix_map;
        public bool include_canonical_examples;
    }

    [Serializable]
    public sealed class PreflightValidateWritePayloadRequestDto
    {
        public const string ToolName = "preflight_validate_write_payload";
        public static readonly string[] RequiredFields = new[] { "tool_name", "payload" };

        public string thread_id;
        public string tool_name;
        public string payload;
    }

    [Serializable]
    public sealed class SetupCursorMcpRequestDto
    {
        public const string ToolName = "setup_cursor_mcp";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string mode;
        public string sidecar_base_url;
        public bool dry_run;
    }

    [Serializable]
    public sealed class VerifyMcpSetupRequestDto
    {
        public const string ToolName = "verify_mcp_setup";
        public static readonly string[] RequiredFields = new string[0];

        public string thread_id;
        public string mode;
    }

    [Serializable]
    public sealed class GetUnityTaskStatusRequestDto
    {
        public const string ToolName = "get_unity_task_status";
        public static readonly string[] RequiredFields = new[] { "job_id" };

        public string thread_id;
        public string job_id;
    }

    [Serializable]
    public sealed class CancelUnityTaskRequestDto
    {
        public const string ToolName = "cancel_unity_task";
        public static readonly string[] RequiredFields = new[] { "job_id" };

        public string thread_id;
        public string job_id;
    }

    [Serializable]
    public sealed class SubmitUnityTaskRequestDto
    {
        public const string ToolName = "submit_unity_task";
        public static readonly string[] RequiredFields = new[] { "thread_id", "idempotency_key", "user_intent", "based_on_read_token", "write_anchor" };

        public string thread_id;
        public string idempotency_key;
        public string approval_mode;
        public string user_intent;
        public string based_on_read_token;
        public string write_anchor;
        public string context;
        public string[] file_actions;
        public string[] visual_layer_actions;
    }

    [Serializable]
    public sealed class ApplyScriptActionsRequestDto
    {
        public const string ToolName = "apply_script_actions";
        public static readonly string[] RequiredFields = new[] { "based_on_read_token", "write_anchor", "actions" };

        public string based_on_read_token;
        public string write_anchor;
        public string[] actions;
        public string[] preconditions;
        public bool dry_run;
        public string thread_id;
        public string idempotency_key;
        public string user_intent;
        public string approval_mode;
    }

    [Serializable]
    public sealed class ApplyVisualActionsRequestDto
    {
        public const string ToolName = "apply_visual_actions";
        public static readonly string[] RequiredFields = new[] { "based_on_read_token", "write_anchor", "actions" };

        public string based_on_read_token;
        public string write_anchor;
        public string[] actions;
        public string[] preconditions;
        public bool dry_run;
        public string thread_id;
        public string idempotency_key;
        public string user_intent;
        public string approval_mode;
    }

    [Serializable]
    public sealed class SetUiPropertiesRequestDto
    {
        public const string ToolName = "set_ui_properties";
        public static readonly string[] RequiredFields = new[] { "based_on_read_token", "write_anchor", "operations" };

        public string based_on_read_token;
        public string write_anchor;
        public string[] operations;
        public bool atomic;
        public string[] preconditions;
        public bool dry_run;
        public string thread_id;
        public string idempotency_key;
        public string user_intent;
        public string approval_mode;
    }

    [Serializable]
    public sealed class SetSerializedPropertyRequestDto
    {
        public const string ToolName = "set_serialized_property";
        public static readonly string[] RequiredFields = new[] { "execution_mode", "idempotency_key", "based_on_read_token", "write_anchor_object_id", "write_anchor_path", "target_object_id", "target_path", "component_type", "property_path", "value_kind" };

        public string execution_mode;
        public string thread_id;
        public string idempotency_key;
        public string based_on_read_token;
        public string write_anchor_object_id;
        public string write_anchor_path;
        public string target_object_id;
        public string target_path;
        public string component_type;
        public int component_index;
        public string property_path;
        public string value_kind;
        public int int_value;
        public double float_value;
        public string string_value;
        public bool bool_value;
        public bool dry_run;
    }

    [Serializable]
    public sealed class HitTestUiAtScreenPointRequestDto
    {
        public const string ToolName = "hit_test_ui_at_screen_point";
        public static readonly string[] RequiredFields = new[] { "x", "y" };

        public string thread_id;
        public string view_mode;
        public int x;
        public int y;
        public int reference_width;
        public int reference_height;
        public int max_results;
        public int timeout_ms;
    }
}
